Add RessourceController to get the string ressource properties
xcomponent/XComponent.Functions pull request #26
Opened 2018-03-23 14:34 UTC by mbarekh

2018-03-23 14:47 UTC, maurelio1234 requested changes
Add unit tests

2018-03-23 14:47 UTC, maurelio1234 commented on src/XComponent.Functions/Controllers/RessourceController.cs
> +        [SwaggerResponse(HttpStatusCode.NoContent, "No ressource available")]
it's a list, return an empty list if there's nothing.
it will make the service simpler

2018-03-23 14:47 UTC, maurelio1234 commented on src/XComponent.Functions/Core/IFunctionsFactory.cs
> +        void SaveRessources(string componentName, string key, string value);
AddKeyValuePair?

2018-03-23 14:47 UTC, maurelio1234 commented on src/XComponent.Functions/Core/IFunctionsFactory.cs
> +        List<FunctionsFactory.KeyValuePairSettingsItem> GetKeyValuePairs();
`FunctionsFactory.KeyValuePairSettingsItem`

you add a dependency from the interface to the implementation, that's not good.
move `KeyValuePairSettingsItem` to an independent class

2018-03-26 09:16 UTC, mbarekh commented
test this please

2018-03-26 12:30 UTC, fredericcarre commented
test

2018-03-27 07:16 UTC, maurelio1234 commented on src/XComponent.Functions/Controllers/RessourceController.cs
> +        [SwaggerResponse(HttpStatusCode.NoContent, "No ressource available")]
Update documentation

2018-03-27 07:16 UTC, maurelio1234 commented on src/XComponent.Functions/Core/KeyValuePairSettingsItem.cs
> +            Console.WriteLine(">EEEEEEEEEEEE");
Remove

2018-03-27 07:16 UTC, maurelio1234 commented on src/XComponent.Functions.Integration.Test/ControllersTest.cs
> +            var address = $"http://127.0.0.1:{Port}/api/Ressource";
Ressource is french, Resource is english

2018-03-28 13:12 UTC, maurelio1234 requested changes

2018-03-28 13:12 UTC, maurelio1234 commented on src/XComponent.Functions/Controllers/StringResourcesController.cs
> +//        [HttpGet]
remove

2018-03-28 13:12 UTC, maurelio1234 commented on src/XComponent.Functions/Controllers/RessourceController.cs
> +        [SwaggerResponse(HttpStatusCode.NoContent, "No ressource available")]
So?

2018-03-28 13:36 UTC, maurelio1234 submitted a review, later dismissed

2018-03-28 13:56 UTC, maurelio1234 approved these changes

2018-03-28 13:57 UTC, merged